### ISSUE TITLE
Setup SQL Alchemy

### ISSUE THREAD

**Issue by jakemorr** [bcgov/epr#4]
**Describe the task**
Setup SQL Alchemy 

**Acceptance Criteria**
- [x] have some basic table thats hooked into ORM and things are fully automated for the initial schema of DB 
- [x] declare a mapping 
- [x] created a schema
- [x] https://docs.sqlalchemy.org/en/13/orm/tutorial.html

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by Nkuruba** [comment]
Implemented SQLALCHEMY to connect to database and created a test to successfully create a table and add a record.

https://github.com/bcgov/epr/pull/16
